Update build-docker.yml

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -52,11 +52,15 @@ jobs:
         id: check
         run: |
           TAG=${{ needs.set-tag.outputs.tag }}
-          if docker manifest inspect ${{ env.REPO_DOCKERHUB }}:$TAG > /dev/null 2>&1; then
+          if docker buildx imagetools inspect ${{ env.REPO_DOCKERHUB }}:$TAG > /dev/null 2>&1; then
             echo "skip_build=true" >> $GITHUB_OUTPUT
           else
             echo "skip_build=false" >> $GITHUB_OUTPUT
           fi
+
+      - name: Debug inspect
+        run: |
+          docker buildx imagetools inspect ${{ env.REPO_DOCKERHUB }}:${{ needs.set-tag.outputs.tag }} || echo "inspect failed"
   
       - name: Debug skip_build output
         run: echo "SKIP_BUILD=${{ steps.check.outputs.skip_build }}"
